services:
  
  #certbot:
  #  image: certbot/certbot
  #  container_name: certbot
  #  volumes:
  #  - ./data/certbot/conf:/etc/letsencrypt
  #    - ./data/certbot/www:/var/www/certbot
  #  entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done;'
    #depends_on:
    #  - openvidu
  #  logging:
  #    driver: "json-file"
  #    options:
  #      max-size: "10m"
  #      max-file: "1"
  #  networks:
  #    - webnet
  
  frontend:
    image: frontend
    container_name: frontend
    environment:
      VITE_JAVASCRIPT_KEY: 5c30369841f6396ec240879963ece715
      VITE_KAKAO_MAPS_API_KEY: a35aa3b39ddb54e12c6f9bc39412f2ef
      VITE_FIREBASE_API_KEY: AIzaSyDboYjroza0kfRATte9r7ggJcSP8FdbfR4
      VITE_FIREBASE_AUTH_DOMAIN: ssafy-711e4.firebaseapp.com
      VITE_FIREBASE_PROJECT_ID: ssafy-711e4
      VITE_FIREBASE_STORAGE_BUCKET: ssafy-711e4.appspot.com
      VITE_FIREBASE_MESSAGING_SENDER_ID: 126751896184
      VITE_FIREBASE_APP_ID: 1:126751896184:web:d194950fe86b5ab47bb38d
      VITE_FIREBASE_MEASUREMENT_ID: G-HS80MRC1HT
      VITE_FIREBASE_DATABASE_URL: https://ssafy-711e4-default-rtdb.asia-southeast1.firebasedatabase.app
      TZ: Asia/Seoul
    ports:
      - "5080:5080"
    volumes:
      - ./data/nginx-frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/logs:/var/log/nginx
   # networks:
   #   - webnet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./data/jenkins:/var/jenkins_shared
      - /var/run/docker.sock:/var/run/docker.sock  
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose 
      - /usr/bin/docker:/usr/bin/docker 
      - /home/ubuntu/plog:/home/ubuntu/plog
      - ./gcp:/var/cache/jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      JENKINS_OPTS: --prefix=/jenkins
      GOOGLE_APPLICATION_CREDENTIALS: ./gcp/ssafy-429607.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    #networks:
    #  - webnet

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    #networks:
    # - webnet

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: boricori
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib
      - ./mysql/dump:/var/lib/mysql
    #networks:
    #  - webnet

  backend:
    image: backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_HIKARI_JDBC-URL: jdbc:mysql://mysql:3306/boricori?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_HIKARI_USERNAME: ssafy
      SPRING_DATASOURCE_HIKARI_PASSWORD: ssafy
      SPRING_DATASOURCE_HIKARI_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_HIKARI_MINIMUM-IDLE: 50
      SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE: 50
      SPRING_DATASOURCE_HIKARI_IDLE-TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_MAX-LIFETIME: 2000000
      SPRING_DATASOURCE_HIKARI_CONNECTION-TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_AUTO-COMMIT: true
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: ANZHut0CJ5HcIog8NeQuX6jegoQ1ffmC
      JWT_SECRET: AJr9yFUVEiJosi1sLu1DLu86IAsgcBn
      GOOGLE_APPLICATION_CREDENTIALS: ./gcp/ssafy-429607.json
    ports:
      - "8088:8088"
    #networks:
    #  - webnet
    volumes:
      - ./gcp/ssafy-429607.json:/gcp/ssafy-429607.json
    depends_on:
      - mysql
      - redis

#networks: 
#  webnet:

volumes:
  jenkins_home:
